# Generated by Django 4.1.3 on 2022-12-04 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProductUserEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engagement",
                    models.CharField(
                        choices=[("LIKE", "Like"), ("DISLIKE", "Dislike")], max_length=8
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="example_app.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="productuserengagement",
            index=models.Index(
                fields=["user", "product"], name="example_app_user_id_3d4a39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productuserengagement",
            index=models.Index(
                fields=["product", "engagement"], name="example_app_product_3f6842_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productuserengagement",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_user_product"
            ),
        ),
    ]
